server {
    listen 80;
    server_name 18.188.211.61.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 18.188.211.61.nip.io;

    ssl_certificate     /etc/letsencrypt/live/18.188.211.61.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/18.188.211.61.nip.io/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass         http://server:8000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
